kubersoftware_configs:
    microservices:

        api_gateway:
            old_sound_rabbit_mq:
                connections:
                    logging:
                        url: '%env(RABBITMQ_URL)%'
                        read_write_timeout: 4
                        heartbeat: 2
                    default:
                        url: '%env(RABBITMQ_URL)%'
                rpc_clients:
                    # АВТО Добавить название rpc_client, получаем из названия микросервиса
                    api_gateway:
                        connection: default #default: default
                        unserializer: json_decode #default: unserialize
                        lazy: true #default: false
                        direct_reply_to: false
            variables:
                user_token_lifetime: '+1 hours'



        nosql_manager:
            old_sound_rabbit_mq:
                connections:
                    logging:
                        url: '%env(RABBITMQ_URL)%'
                        read_write_timeout: 4
                        heartbeat: 2
                    default:
                        url: '%env(RABBITMQ_URL)%'
                rpc_server:
                    connection: default
                        # АВТО Добавить callback: имя_микросервиса_server
                        callback: nosql_manager_server
                        qos_options: { prefetch_size: 0, prefetch_count: 1, global: false }
                        exchange_options: { name: random_int, type: topic }
                        queue_options:
                            # АВТО Добавить name: имя_микросервиса_queue
                            name: nosql_manager_queue
                            routing_keys:
                                # Default key
                                -
                                # UserTokenEntity
                                - 'insertOneUserTokenEntity'
                                - 'findOneByUserToken'
                            durable: false
                            auto_delete: true
                        serializer: json_encode



        api_doc:
            variables:
                file_path: '/var/www/html/public/doc.json'
                version_date_format: 'Y-m-d'
                version_datetime_format: 'Y-m-d_H:i:s'



