kubersoftware_configs:
    microservices:

        api_gateway:
            old_sound_rabbit_mq:
                connections:
                    logging:
                        url: '%env(RABBITMQ_URL)%'
                        read_write_timeout: 4
                        heartbeat: 2
                    default:
                        url: '%env(RABBITMQ_URL)%'
                rpc_clients:
                    api_gateway:
                        connection: default #default: default
                        unserializer: json_decode #default: unserialize
                        lazy: true #default: false
                        direct_reply_to: false
            variables:
                user_token_lifetime: '+1 hours'



        nosql_manager:
            old_sound_rabbit_mq:
                connections:
                    logging:
                        url: '%env(RABBITMQ_URL)%'
                        read_write_timeout: 4
                        heartbeat: 2
                    default:
                        url: '%env(RABBITMQ_URL)%'
                rpc_server:
                    nosql_manager:
                        connection: default
                        callback: nosql_manager_server
                        qos_options: { prefetch_size: 0, prefetch_count: 1, global: false }
                        exchange_options: { name: nosql_manager, type: topic }
                        queue_options:
                            name: nosql_manager_queue
                            routing_keys:
                                - ''
                                - 'insertOneUserTokenEntity'
                                - 'findOneByUserToken'
                            durable: false
                            auto_delete: true
                        serializer: json_encode



        api_doc:
            old_sound_rabbit_mq:
                connections:
                    logger:
                        url: '%env(RABBITMQ_URL)%'
                        read_write_timeout: 4
                        heartbeat: 2
                    default:
                        url: '%env(RABBITMQ_URL)%'
                        read_write_timeout: 4
                        heartbeat: 2
                consumers:
                    api_doc:
                        connection: default
                        exchange_options: { name: 'api_doc', type: direct }
                        queue_options: { name: 'api_doc_queue' }
                        callback: message_service
            variables:
                file_path: '/var/www/html/public/doc.json'
                version_date_format: 'Y-m-d'
                version_datetime_format: 'Y-m-d_H:i:s'



        notifier:
            old_sound_rabbit_mq:
                connections:
                    default:
                        url: '%env(RABBITMQ_URL)%'
                        read_write_timeout: 4
                        heartbeat: 2
                consumers:
                    notifier:
                        connection: default
                        exchange_options: { name: 'notifier', type: fanout }
                        queue_options: { name: 'notifier_queue' }
                        callback: notifier_consumer



        logger:

